### PR TITLE
Close registration

### PR DESCRIPTION
**Pull request by mduemcke**
The status of the registration is persisted in the database in its own table. This is maybe not ideal? Any suggestions how to improve this are welcome!

### CODE REVIEW

**Comment by lplotni** [comment]
Hmmm... the only option I see, is to store it in a file. But as we will have some more data this nature to persist in the future (like *start time*), I would leave it in the db and switch to [JSON though](http://www.postgresql.org/docs/9.4/static/datatype-json.html) so that it's more suited to a key/value stuff. Opinion?

Apart from that, we still need to offer the admin the possibility to actually **close** the registration (e.g. button on the admin page).

**Comment by mduemcke** [comment]
@lplotni Yep, if we store more data than just the registration status, then this setup makes more sense, especially with JSON.

For actually closing in the UI: this will be part of the "generate start numbers" (once the generation is triggered, the registration will be closed). I separated both functionalities in separate branches for more clarity. The branch to generate the PDFs with the start numbers is still WIP.
I will add an extra confirmation before closing the registration, as there is as far as I know currently no plan to be able to re-open the registration from the UI.

**Comment by lplotni** [comment]
Closing the registration by triggering the **start numbers creation** <- me like it :smile: 

Do you think we should merge this PR and create a new one for the JSON table or do you want to amend this PR?

**Comment by mduemcke** [comment]
There is no rush to merge this PR, I will amend it

**Comment by lplotni** [comment]
Are you done with this functionality, should I try to merge?

**Comment by mduemcke** [comment]
@lplotni It's not yet ready, I just merged the branch with the update from the master branch and didn't have time yet to continue with the actual functionality. I will let you know once it is ready to be merged.

**Comment by lplotni** [comment]
Roger

**Comment by mduemcke** [comment]
@lplotni This branch is now ready to be merged :) Now using JSONB to retrieve the registration status.
I also decoupled the start number generation and the closing of the registration as discussed last Saturday. The registration can be closed (and re-opened) from the admin page.

**Pull request merged**
