### PR TITLE
Implementing live updates for results

### PR DESCRIPTION
**Pull request by sreedhap**
Refer trello card: https://trello.com/c/SudMFCqT/89-live-update-the-results

### CODE REVIEW

**Comment by cz8s** [comment]
I thought the reason why the websockets don't work on docker might be, that we connect to localhost, but the app gets a request from 172.x.x.x. because docker does this network magic with docker-proxy.
But I setting the Host and the Origin headers correctly did not help.
it even works without docker (when the Origin header is clearly wrong)
This is also what the documentation says: It will always allow everyting except you pass a validation function. I tried that, and wrote a function that always returns true. This validation function is not even called when using docker. The connection terminates before ws validates anything.
Long answer short: I still have no clue why this fails :)

**Comment by cz8s** [comment]
Tomorrow I will try to find the unhandled 'error' event. Maybe that will give us a clue

**Comment by cz8s** [comment]
started working on this again. its not a docker error. If I just start wscat inside docker, I can talk to it from outside. Still digging ...

**Comment by cz8s** [comment]
closing this one because I cherry-picked all the commits from this one + a docker fix in #317 
Thanks @sreedhap . We should hack more often :)

**Comment by sreedhap** [comment]
Thanks @cz8s , I enjoyed pairing with you! :-)

**Pull request closed without merging**
