### PR TITLE
also show on_site participants

### PR DESCRIPTION
**Pull request by cz8s**
We might need to edit them as admins.
And move them into another start_block

### CODE REVIEW

**Comment by lplotni** [comment]
I don't want to be annoying... but there are no tests in this PR.

**Comment by cz8s** [comment]
I know. I had a look where to do this.  And I couldn't find a nice place.
I could do an integration test. But since this is  a 'select * from from participants', it seems to be the wrong place. Maybe I manage to write a functional test later.

**Comment by lplotni** [comment]
But you verified that all works *by hand* 😉  ?

**Comment by cz8s** [comment]
Yup

**Pull request merged**
