### PR TITLE
show who ordered slimfit shirts

### PR DESCRIPTION
**Pull request by cz8s**
there are concerns, that too many people order
slimfit shirts. Make the status visible.

### CODE REVIEW

**Comment by lplotni** [comment]
What do you mean with 'too many people order slimfit' and why should this be problematic?

**Comment by lplotni** [comment]
I merge it although it would be super if you could add some test coverage to that? Or should I put this on the general todo list?

**Comment by cz8s** [comment]
Fear is, that many people(men) order slimfit and then realize the short is too slim...

**Comment by lplotni** [comment]
We could add some additional information to the shirt size selection (providing some measurements or something like this). Good idea/bad idea?

**Comment by cz8s** [comment]
Feedback:
Ich fände es jetzt auch besser, wenn wir das "Slim fit" in doch in   "tailliert / schmächtige Menschen" ändern könnten.           
Oder wir lassen es bei "Slim fit" und "Normal fit" und geben noch den Link  
zur Größentabelle

**Pull request merged**
