### PR TITLE
Serverside filter

### PR DESCRIPTION
**Pull request by nhellwig**
Implemented Tests, UI and Backend of participants and result page for server-side filtering and paging

### CODE REVIEW

**Comment by cz8s** [comment]
it works for me locally. Investigating ....

**Comment by cz8s** [comment]
the snap config now works. the errors now really come from failing tests \o/
Lets see why they don't fail on local machines ...

**Comment by nhellwig** [comment]
Yeah I've seen this admin test fail from time to time. I think it might be because of not waiting for the page to refresh after the button has been pressed. But that's only an idea. The same happens from time to time on my local machine with the master branch also.

**Comment by cz8s** [comment]
closing to trigger new travis build

**Comment by cz8s** [comment]
triggering ...

**Pull request merged**
