### PR TITLE
wip: Generate certificates

### PR DESCRIPTION
**Pull request by cz8s**
still ugly, but works. all data fields are showing.
Waiting for the template before I start ordering them

### CODE REVIEW

**Comment by cz8s** [comment]
almost done. the tests fail because of the changes in how the time is calculated now with two starts.
Will have a look tomorrow

**Comment by lplotni** [comment]
I'm getting:
```
  generateCertificate
      should generate one certificate: failed

Failures:
1) pdfGeneration generateCertificate should generate one certificate
1.1) Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
```

Is all the code already here?

**Comment by cz8s** [comment]
hmm. should be. it works on snap. the error there is, that it can not calculate the correct starttime anymore. but it doesn't fail with a timeout.

**Comment by cz8s** [comment]
strange. they are green on my machine. I checked the repo out into another directory and they are green there...
Lets have a look tomorrow.

**Pull request merged**
